const biography = {
    shortBio: {
        textBlocks: [
            `I was born and raised on Long Island, and spent a good deal of my youth playing sports on our street and watching every TV Western ever made.`,
            `I began the violin at age 7 under the instruction of everyone's most important teacher, the first. Amadeo “Bill” Liva, an accomplished violinist, did “house calls” as a violin teacher, as did doctors in that bygone ere. In later years, my main violin teachers were Ivan Galamian, the famous teacher at Juilliard and Curtis, and Joseph Silverstein, former concertmaster of the Boston Symphony. After graduating from Yale University in 1975, I joined the Boston Symphony violin section. In 1988, I won the associate concertmaster position at the Utah Symphony, which I held until resigning in 2011.`,
            `Along the way, I was on the faculty of the University of Utah School of Music, first violin of the Abramyan String Quartet, and since 2004 have been the music director of the Vivaldi by Candlelight chamber orchestra series in Salt Lake City. I have been a guest conductor of the Salt Lake Symphony and in orchestras in Ecuador and Peru.`,
            `My music compositions have been performed in such divergent settings as the Moab Music Festival and the Pittsburgh Symphony.`,
            `In 2009, my first mystery novel, Devil's Trill, was published and was a Barnes and Noble Discover Great New Writers selection. That has been followed by seven additional novels in the Daniel Jacobus series, and numerous other fiction and nonfiction books.`,
            `In 2021, my wife and I relocated from Salt Lake City to Seattle in order to be hands-on grandparents to our two darling grandchildren, and have loved every minute of it.`
        ],
        image: `short-bio.png`,
    },
    longBio: {
        textBlocks: [
            `As a kid growing up on Long Island in the '50s, my dream was to play first base with the New York Yankees. For some reason, I never did receive a call from the Yankee brass. Though I still haven't given up hope, it became necessary in the meantime to make a living. So at the age of eight I started playing the violin, studying with an inspirational Juilliard-trained teacher, Amadeo William Liva. In 1966 I began four years of private lessons with the legendary Ivan Galamian until graduating Westbury High in 1970. While in public school I was concertmaster of the Long Island Youth Orchestra, conducted by Martin Dreiwitz. Not only was it a terrific orchestra, Mr. Dreiwitz, a professional travel agent, schlepped the orchestra on international tours every summer. What an experience as a teenager to perform the Saint Saens “Havanaise,” Bruch “Scottish Fantasy,” and Mozart Symphonie Concertante on four continents! This no doubt accounts for my lifetime wanderlust.`,
            `In 1969 I attended the Boston University Tanglewood Institute, beginning a relationship with Tanglewood that has lasted to this day. In the same year I was selected to participate in the very first New York String Seminar, led by the inimitable Alexander Schneider. With soloists Isaac Stern and Jean Pierre Rampal, this experience opened my eyes to a lofty new world of ensemble playing. After two wonderful years at the Oberlin College Conservatory, where my teachers were David Cerone and Christopher Kimber, I transferred to Yale to study with the renowned concertmaster of the Boston Symphony, Joseph Silverstein. During my college days I attended Norfolk Chamber Music Festival where I was coached by members of the Guarneri String Quartet and Claude Frank, the Sarasota Music Festival, and the Tanglewood Music Festival. I received a Bachelor of Arts degree (cum laude) from Yale College simultaneously with a Master of Music from the Yale University School of Music in 1975.`,
            `Still not having heard from the Yankees, I auditioned for and won a position with the Boston Symphony, joining that august ensemble at the age of twenty-two, and remained a member of the violin section for thirteen years. I performed as soloist with the Boston Pops under Arthur Fiedler and John Williams, was a member of the renowned Elias/Lefkowitz Violin Duo (or, as my partner recalls it, the Lefkowitz/Elias Violin Duo), and of the Andover Trio.`,
            `In 1986-87, I took a sabbatical leave from the BSO and divided the year between Japan, Australia, and New Zealand, where I performed, taught, and conducted. My wife, Cecily, and I took our two children, Kate and Jacob, who were 28- and 8-months old when we departed, and provided them with an early world view. Some of Jake's first solid food, in fact, was ground-up sushi. Another part of the adventure was being called upon to conduct a fully staged performance of La Traviata at the Innisfail (Australia) Opera Festival on short notice.`,
            `It was westward ho for my family in 1988, after I won the audition for Associate Concertmaster of the Utah Symphony. The move to Utah turned out to be providential, offering extensive performance, teaching, and eventually conducting opportunities. I performed concertos with the orchestra, was a faculty member of the University of Utah, was the founding first violinist of the Abramyan String Quartet, had several of my compositions receive their first performances, and became music director of the Vivaldi By Candlelight chamber music series in 2004.`,
            `Many other positive things came my way as well, one of which was a re-connection with the BSO, where I've regularly performed with the orchestra during the summer at Tanglewood. Another development was the establishment of an ongoing relationship with music-making in Peru and Ecuador, where I had numerous opportunities to conduct, perform, and teach, and with a Fulbright grant in 2008, I was a guest professor of the National Conservatory in Lima.`,
            `In 1997 a second sabbatical leave, this one from the Utah Symphony, took our family to Umbria, Italy. It was a great year of eating, drinking, exploring the Umbrian countryside, and immersing ourselves in the culture and history of Italy.`,
            `But it wasn't all fun and games. I did a lot of composing, and significantly, I wrote my first book, Devil's Trill. The ensuing years brought innumerable rewrites, but eventually I found an agent, Josh Getzler, at Writer's House in New York, who ultimately found me a publisher, St. Martin's Press. Devil's Trill, a murder mystery which takes place in the classical music world (go figure!) was published in 2009, and has been followed by seven more installments of the series. (Please see my Writing page for more details about the Daniel Jacobus mystery series and other books I've written.)`,
            `In May of 2011, I bid a fond farewell from full-time symphony playing. However, I've continue to concertize, publish, and compose. There have been more books, more concerts, and more exciting challenges. One very exciting development has been a recent recording I made of the Opus 1 Violin Sonatas by the Baroque violinist-composer Pietro Castrucci, to be released in early 2022 by Centaur Records. Not only is the music exquisite, it's the first complete recording of these 12 sonatas ever!`,
            `In 2021, I relocated to Seattle, where I have begun to connect with multifaceted cultural scene, performing on a Baroque violin in addition to a beautiful violin my son, Jacob, made for me, and meeting with book clubs and doing book events. I look forward to continue to expand my music and literary horizons both in Seattle and in our little cottage in the woods in western Massachusetts.`
        ],
        image: 'long-bio.jpeg',
    }
}

export default biography;