const blogs = {
    index: {
        "2023": [
            "The Day After Memorial Day",
        ]
    },
    blogsContent: {
        "The Day After Memorial Day": {
            name: "The Day After Memorial Day",
            date: "MAY 31, 2023",
            textBlocks: [
                `Old Franz Eisich recited their names, one by one, as he passed by their graves on his mower. Sewalls, Pikes, Johns. The Spencers. He knew all the families by heart. The names, and the dates and epitaphs, too. Except for those under slate stones so old that all the writing had worn off long before he ever got there. Or the little ones that only had the initials of the babes who died in their mother’s arms. No one would ever know who they had been, but they were almost like his friends and he felt they knew him, too. And that odd coffin-sized patch of darker green. When his mind wandered, as had been happening more often of late, Franz wondered, is there was someone underneath there, too? And if so, could whoever was hear his mower passing over it?`,
                `Franz had tended the Rockdale graveyard since he was fourteen. Yet in all his many years, he couldn’t remember such intense heat the day after Memorial Day. Still only May and so unseasonably, unreasonably hot. And no breeze, either. They still called it the Rockdale graveyard though the hamlet of Rockdale itself, which preceded the American Revolution, became a ghost town after the train stopped coming through in the ‘30s and then was swallowed up entirely by the forest until no trace of it was left except the graveyard and vanishing memories of the old folks. And soon even those would be gone.`,
                `When the county had originally hired Franz they handed him a push mower and paid him a dollar per. He thought he would only do it for one summer because they felt sorry for him, but they kept on hiring him because he was conscientious about keeping the grass trim and well-manicured all the way up to the stones. And though no one had been buried in the graveyard since 1956, the county had wanted the little cemetery surrounded by the encroaching woods to look tidy because it was visible from the road. When times became flush, the county provided him with a John Deere rider mower, and at the end they were paying him thirty-five dollars per mowing, which, at that point in his simple life, was sufficient. But after twenty-eight years the county decided that spending money to maintain the Rockdale graveyard was a frill. Nevertheless, Franz continued to tend it on his own accord. Descendants of the deceased had a right to see the graves of their ancestors properly cared for, he thought, and as the county had by that time long forgotten about the mower, it was no problem.`,
                `Because grass grows faster in a graveyard, Franz always made it a point to mow it within a few days of Memorial Day because he wanted it to look nice on the one day in the whole year that more than the curious passer-by would pay a visit.  Descendants, friends, and those who simply remembered left things: flowers, little American flags, pinwheels, balloons. Even dolls and other trinkets. For as long as he could remember, the grave of little Ashton Spencer, 1846-1849, always had a bowl of plums gracing it on Memorial Day weekend, which Franz found very curious.`,
                `Since he usually mowed the lawn only one, two, or at most three days before Memorial Day, Franz didn’t need to get back to the graveyard until a week later, by which time the bouquets had wilted. He would collect them and the gifts, and because none were worth anything, threw them all out. The plums, though, were always gone by the time he returned, and he often wondered who would be so callous to steal something like that.`,
                `This past week, Franz had needed to revise his traditional schedule because of his eyes. They were going bad. His son, Eric, had arranged an appointment with a specialist in Pittsfield to do tests on Wednesday. They told him he’d have to stay out of the light for a few days after. His granddaughter, Josie, was going to drive him there, showing off with her new driver’s license, because he didn’t drive. The John Deere was the only vehicle they decided was safe enough for him to sit behind the wheel in. Not that that was much of a consolation prize. The darn thing was getting harder and harder to start, and the engine was making a heck of a racket. Franz made sure to fill the tank with gasoline because once he got it started he sure as heck wasn’t going to turn it off until it was back in his barn.`,
                `So on the day after Memorial Day, Franz circled the half-dead oak tree in the center of the Rockdale graveyard. Before ’78—or was it ’79—when the tornado blew through and lightning struck the tree, which until then had been sort of a natural sundial, casting a circulating shadow over all the graves over the course of the day. The tornado’s path had left a flattened truck stop down the road and teased the edge of the graveyard. No one had been killed, but folks at the truck stop, having barely evaded death, joked that if they had died at least the graveyard would’ve been in good shape. A few headstones had been knocked over, which Franz subsequently reset with great care, but that was the extent of the damage. The oak, which might well have been even older than the graveyard itself, had been split right down the middle, and the shadow it cast no longer kept good time. One half of it died, though it’s charred skeleton stubbornly refused to surrender to gravity. The other half acted as if nothing had happened. In the dead of winter the two halves couldn’t be told apart, but now the live half, its pale green spring foliage, tender and vulnerable, provided the graveyard’s only shade.`,
                `Franz chose that cool spot under the living half to pull the brake on his mower.  The little sunlight sneaking through the leaves painted a mask of dappled light on his face. He wiped his face with his handkerchief, removing the sweat but not the shadows. He had brought a canteen of water with him, but as his labor was almost complete, he decided that he would wait to quench his thirst.`,
                `A pair of puppies bounded out of the woods, puffballs of brown-black fur with not a care in the world, chasing tails and rolling each other over. Newfoundlands. Franz had had many a dog in his day, but never a Newfie. Only mutts. Or mixed breeds, Franz thought, as they call mutts today. Smarter and healthier than purebreds, mutts are. Better companions than people.`,
                `The pups ambled around the graveyard, sniffing as they went, ending their expedition at little Ashton Spencer’s headstone, where they ravenously began to devour the bowl of plums.`,
                `Mystery solved! Franz got off the mower to move in for a closer look, his eyesight being so poor. He left the engine running, though. He wasn’t going to take any chances of not being able to restart it. The pups, intent on enjoying their snack, paid him no heed as he approached. If only the folks who had brought the plums knew where their devotional gift was going! Should he tell them?`,
                `He was right behind the pups now, and bent over to gently shush them away.`,
                `He squinted. They weren’t puppies. They weren’t dogs at all.`,
                `Suddenly enshrouded by an unlikely shadow, Franz looked over his shoulder. An explosive blow to his forehead drove Franz to the ground. He was dazed and his head throbbed. His cheek pressing against the cool and moist dark patch of green he had just mown, Franz felt his hot blood begin to drip around his ears and mix with fresh, sweet-smelling grass clippings. He groaned and agonizingly rolled onto his back.`,
                `A mother bear, standing on its hind legs, was over six feet tall, her shadow enveloping Franz. He had seen bears before. Black bears. There had been more and more sightings of them recently—even reports of them breaking into houses and rifling through refrigerators—but no one had ever been attacked by one. At least to his knowledge.`,
                `A painful glow from the setting sun, stinging his failing eyes, formed a pulsating, read halo around the bear. What was it they say you’re supposed to do if you’re confronted by a bear? Franz tried to remember. Stand up tall and make yourself look big, or roll into a fetal ball and play dead? Be silent, or yell in a high voice? Slowly back away, or run like heck? One thing he was sure of. Never get between a mother and its cubs.`,
                `His friend Joe always carried a long stick with him just in case, to hold over his head to make himself look taller because he said bears have bad eyesight. A funny thought popped into Franz’s head that the bear should go with him to the specialist in Pittsfield.`,
                `If he could make it to the John Deere, maybe he could escape. Thank God he had left it running. Franz propped himself up on his elbows.`,
                `“Mama,” Franz said. “I mean you and your pups no harm.”`,
                `The bear hovered over him.`,
                `“You hear? This ain’t my time. I still got work to do.”`,
                `The bear carried the stench of carrion and made Franz want to vomit. The two cubs, having finished their plums, approached Franz warily. Deciding he was a new adventure, they pounced on his stiffening legs and tore on the cuffs of his overalls. Franz, dizzy, remained motionless, eyes fixed on the mother, willing it to understand. The bear raised its forearm and extended its clawed paw.`,
                `No one in memory had been killed by a black bear.`,
                `The cubs continued to tug playfully on Franz’s pant leg. As his mind hovered on the edge of consciousness, memories of his German mother long ago resurfaced. He hadn’t thought about her for such a long time.`,
                `A slight breeze rustled the leaves of the old, lightning-blasted oak and stirred the little flags and pinwheels on the graves.`,
                `The gentle tone of the bear’s voice surprised Franz.`,
                `“Gib deine Hand, du schön und zart Gebild!`,
                `Bin Freund, und komme nicht, zu strafen.`,
                `What did it mean? Franz wondered. It sounded like an epitaph.`,
                `Sei gutes Muts! ich bin nicht wild,`,
                `Sollst sanft in meinen Armen schlafen!”`,
                `Soon, the only sound in the Rockdale graveyard was the John Deere engine, and when the fuel was all spent, that, too, went silent, and the grass grew over the gravestones.`,
            ]
        }
    }
}

export default blogs;